[theme]
base = "light"
primaryColor = "#33658A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FAFAFA"
textColor = "#2F4858"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
